### ISSUE TITLE
Serial Problems

### ISSUE THREAD

**Issue by porterj091** [CSUFTitanRover/TitanRover17#17]
When the Pi is restarting it sometimes can't see the serial connection with the Arduino.  This happened a couple of times, but I can't replicate it.  Possible solves for this is to use the reset pin on the Arduino and have it reset once the RoverControl.js process is running.  Or have a switch turn on the Ardiuno after the Pi has turned on.  If it occures the Pi needs to be turned off, then unplug the Arduino.  Restart the Pi then after it has booted plug the arduino back in and udev should see and and link it in the /dev files.

**Comment by sl224** [comment]
http://askubuntu.com/questions/645/how-do-you-reset-a-usb-device-from-the-command-line

We can have ^ launch as a service upon bootup if really necessary.
