### ISSUE TITLE
Raspi loses time accuracy

### ISSUE THREAD

**Issue by Weffe** [CSUFTitanRover/TitanRover17#18]
When the raspi is left unconnected to the internet for long time periods its unable to sync up the Global NTP (Network Time Servers). This causes its local time to become inaccurate which affects the timestamps sent in each data packet to be stored on the MongoDB Server. This becomes a problem because when trying to query data by a timerange then the start and end times won't be insync and will be offset. 

The raspi being unconnected to the internet for only a couple of days caused around a 4 hour offset of time accuracy.

**Comment by Weffe** [comment]
In order to prevent this from happening just make sure to connect it to the internet and force a time sync. We should do this right before starting any missions to make sure timestamps are accurate.

**Comment by sl224** [comment]
@Weffe im dont think we'll have any internet access out in the desert
@stewartjustind right?

**Comment by skrapmi** [comment]
I can hook up an RTC for it to pull time from.

**Comment by stewartjustind** [comment]
@shan224 You are absolutely right. We have zero internet access on site. But, we do have internet access at the hotel that we are at before we leave for competition. Hotel is about 15 minutes away from competition site, and then factor in setup and getting ready so the last time we will be connected is probably 2 hours before competition. So depending on how long it takes for it to go out of sync, we might be okay.

**Comment by Weffe** [comment]
If this is the case, we either need to test how long it takes for the pi to go out of sync or find a more reliable value for timestamps which I don't know what that could be. Couldn't we also use someone's phone as a wifi hotspot to sync up time?

**Comment by stewartjustind** [comment]
@weffe Problem with using someones phone is that out in the desert, I am pretty sure our cell coverage was close to nothing as well. I think @skrapmi had a good idea, just hook up an RTC that we can use to keep the timing constant.

**Comment by Weffe** [comment]
Okay looks like we've solved this issue.
