### ISSUE TITLE
Test Raspberry Pi 3 Code on Titan I mobility system.

### ISSUE THREAD

**Issue by stewartjustind** [CSUFTitanRover/TitanRover17#2]
Need to test the differential steering algorithm on the Raspberry Pi 3.

**Comment by stewartjustind** [comment]
Added the PWM example to repository. We can use this to allow us to send out the proper PWM signals. The Sabretooth ESC expects values between 1000-2000 us (microseconds). 1000 being full reverse, 1500 is stop, and 2000 is full forward.

**Comment by stewartjustind** [comment]
Mobility code was tested on the prototype. Small issues with the XY axis were discovered and fixed. Further testing proved TCP to be unreliable. Moved to UDP. More refinements are necessary.

**Comment by sl224** [comment]
We've moved to serial communication 

 rpi <-> arduino mega -> sabretooth escs
