### ISSUE TITLE
Figure out how to use new Emlid Reach GPS unit.

### ISSUE THREAD

**Issue by stewartjustind** [CSUFTitanRover/TitanRover17#9]
New GPS unit is in. Lets start integrating it into our mobile platform. 
https://docs.emlid.com/reach/

**Comment by skrapmi** [comment]
1.  Communication
     a.  i2c
          - does not work and Emlid representative, in forums, commented they have no plans to fix it
     b. UART
          - protocol doesn't produce data that can be used for the moment
     c. Server (Currently Working With)
          - Reading RTKLIB to work with command line options
          - RTKLIB is in C a little more difficult to work in
